export const font = {
    sergioTrendy: `https://ik.imagekit.io/sukhakala2/Fonts/Sergio%20Trendy.ttf?updatedAt=1693195598154`,
    robotoFlex: `https://ik.imagekit.io/sukhakala2/Fonts/RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf?updatedAt=1693195598131`,
    sergioTrendy2:`https://ik.imagekit.io/sukhakala2/Fonts/Sergio%20Trendy%202.ttf?updatedAt=1693195597587`,
    montserratVariable:`https://ik.imagekit.io/sukhakala2/Fonts/Sergio%20Trendy%202.ttf?updatedAt=1693195597587`,
    montserratThinItalic:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-ThinItalic.ttf?updatedAt=1693195597017`,
    montserratThin:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-Thin.ttf?updatedAt=1693195596961`,
    montserratSemiBoldItalic:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-SemiBoldItalic.ttf?updatedAt=1693195596783`,
    montserratSemiBold:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-SemiBold.ttf?updatedAt=1693195594248`,
    montserratRegular:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-Regular.ttf?updatedAt=1693195593994`,
    montserratMedium:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-Medium.ttf?updatedAt=1693195593960`,
    montserratLightItalic:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-LightItalic.ttf?updatedAt=1693195593825`,
    montserratLight:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-Light.ttf?updatedAt=1693195593789`,
    montserratMediumItalic:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-MediumItalic.ttf?updatedAt=1693195593331`,
    montserratItalicVariable:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-Italic-VariableFont_wght.ttf?updatedAt=1693195593027`,
    montserratItalic:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-Italic.ttf?updatedAt=1693195593030`,
    montserratExtraLightItalic:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-ExtraLightItalic.ttf?updatedAt=1693195592926`,
    montserratExtraLight:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-ExtraLight.ttf?updatedAt=1693195592873`,
    montserratBlack:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-Black.ttf?updatedAt=1693195589698`,
    montserratBoldItalic:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-BoldItalic.ttf?updatedAt=1693195589695`,
    montserratExtraBoldItalic:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-ExtraBoldItalic.ttf?updatedAt=1693195589529`,
    montserratExtraBold:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-ExtraBold.ttf?updatedAt=1693195589458`,
    montserratBlackItalic:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-BlackItalic.ttf?updatedAt=1693195589725`,
    montserratBold:`https://ik.imagekit.io/sukhakala2/Fonts/Montserrat-Bold.ttf?updatedAt=1693195589388`,
    brushHsci:`https://ik.imagekit.io/sukhakala2/Fonts/BRUSHSCI.ttf?updatedAt=1693195589407`,
    gentyDemo:`https://ik.imagekit.io/sukhakala2/Fonts/GentyDemo-Regular.ttf?updatedAt=1693195589227`,
    brushScript:`https://ik.imagekit.io/sukhakala2/Fonts/brush%20script%20mt%20kursiv.ttf?updatedAt=1693195589279`,
    gentyDemoRegular:`https://ik.imagekit.io/sukhakala2/Fonts/GentyDemo-Regular.otf?updatedAt=1693195589093`,
}

export const fontString = {
    sergioTrendy:"sergioTrendy",
    robotoFlex:"robotoFlex",
    sergioTrendy2:"sergioTrendy2",
    montserratVariable:"montserratVariable",
    montserratThinItalic:"montserratThinItalic",
    montserratThin:"montserratThin",
    montserratSemiBoldItalic:"montserratSemiBoldItalic",
    montserratSemiBold:"montserratSemiBold",
    montserratRegular:"montserratRegular",
    montserratMedium:"montserratMedium",
    montserratLightItalic:"montserratLightItalic",
    montserratLight:"montserratLight",
    montserratMediumItalic:"montserratMediumItalic",
    montserratItalicVariable:"montserratItalicVariable",
    montserratItalic:"montserratItalic",
    montserratExtraLightItalic:"montserratExtraLightItalic",
    montserratExtraLight:"montserratExtraLight",
    montserratBlack:"montserratBlack",
    montserratBoldItalic:"montserratBoldItalic",
    montserratExtraBoldItalic:"montserratExtraBoldItalic",
    montserratExtraBold:"montserratExtraBold",
    montserratBlackItalic:"montserratBlackItalic",
    montserratBold:"montserratBold",
    brushHsci:"brushHsci",
    gentyDemo:"gentyDemo",
    brushScript:"brushScript",
    gentyDemoRegular:"gentyDemoRegular",

}